# Processo Seletivo Engenheiro de Dados Jr - Mayke Kend

Pensei em manipular uma planilha no Google Sheets usando Python junto com a biblioteca Pandas via Google Colab, no qual vamos salvar alguns dados que foram extraídos da nossa [base de dados](https://docs.google.com/spreadsheets/d/1ta35CQlVuDHchDS6RavnCgHQnlXuRVV9t0oKTbvgB2I/edit#gid=0) em uma página específica do Google Sheets.

Preparado? Então, vamos lá!

Para quem trabalha com dados, às vezes é bem interessante pegar dados de planilhas do Google Sheets ou acrescentar linhas a uma planilha já existente. Para isso, podemos utilizar um pacote python chamado gsprea

# Interagindo com o Google Sheets

>Instalando `gspread`

In [1]:
!pip install --upgrade gspread

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: gspread in /usr/local/lib/python3.7/dist-packages (5.4.0)
Requirement already satisfied: google-auth-oauthlib>=0.4.1 in /usr/local/lib/python3.7/dist-packages (from gspread) (0.4.6)
Requirement already satisfied: google-auth>=1.12.0 in /usr/local/lib/python3.7/dist-packages (from gspread) (1.35.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from google-auth>=1.12.0->gspread) (1.15.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.7/dist-packages (from google-auth>=1.12.0->gspread) (0.2.8)
Requirement already satisfied: setuptools>=40.3.0 in /usr/local/lib/python3.7/dist-packages (from google-auth>=1.12.0->gspread) (57.4.0)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from google-auth>=1.12.0->gspread) (4.2.4)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.7/dist-packages (from google-auth>=1.12.0->gspread) (4.8)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.7/dist-packages (from google-auth-oauthlib>=0.4.1->gspread) (1.3.1)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.7/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=1.12.0->gspread) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.2.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.23.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2022.5.18.1)

# Importando as Bibliotecas e Realizando Autenticação

>Importando as Bibliotecas

In [2]:
from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

>Abrindo planilha JSON_to_Google_Sheets

In [3]:
spreasheet = gc.open('JSON_to_Google_Sheets')

>Abrindo a primeira página da planilha

In [4]:
page = spreasheet.sheet1

>Visualizando a primeira linha da planilha

In [5]:
page.row_values(1)

['name',
 'phone',
 'email',
 'address',
 'postalZip',
 'region',
 'country',
 'list',
 'numberrange',
 'currency']

>Visualizando valor de uma célula específica

In [6]:
page.acell('A2').value

'Jerry Snyder'

>Atualizando uma determinada célula ou deletar informação

In [7]:
# page.update('K1', 'Test')
# page.update('K1', '')

Caso você queira está carregando o Google Sheets em formato de DataFrame por completo, só basta importar a biblioteca Pandas

In [8]:
import pandas as pd

>Criando um DataFrame para que seja visualizado os dados

In [9]:
df = pd.DataFrame(page.get_all_records())

>Visualizando os 5 primeiros dados em uma variável df para DataFrame

In [10]:
df.head()

,name,phone,email,address,postalZip,region,country,list,numberrange,currency
0,Jerry Snyder,1-963-621-3676,molestie.pharetra.nibh@aol.com,631-6614 Quis Road,3715 CO,Ankara,France,11,10,$42.23
1,Evelyn Cortez,(438) 713-1664,eget.ipsum@outlook.org,283-4910 Quis Road,69845,Zaporizhzhia oblast,Sweden,13,5,$62.78
2,Keane Gross,1-681-418-7743,ridiculus.mus@hotmail.net,"P.O. Box 957, 1870 Donec St.",12528,Central Sulawesi,Sweden,11,10,$36.01
3,Illana Collins,(356) 124-0101,eu@protonmail.com,978-5629 Semper Street,76135,Maule,Sweden,13,5,$37.14
4,Hedley Mejia,1-267-247-1174,a@aol.org,"P.O. Box 461, 9908 Luctus Road",3543 LM,Provence-Alpes-Côte d'Azur,Canada,5,4,$10.49

# Abrindo em um DataFrame por Completo

>Aprofundando-se um pouco mais em nossa automação com o Google Sheets. Aqui, pensei em fazer uma query com intuito de visualizar coluna "numberrange" que possui valor igual a 4 e depois inserir esses dados em uma nova página. Então, pasa isso temos que criar outro DataFrame para salvar essa informação

In [11]:
df_numberrange = df.query('numberrange==4')

>realizando leitura do nodo DataFrame que chamamos de df_numberrange

In [12]:
df_numberrange.head()

,name,phone,email,address,postalZip,region,country,list,numberrange,currency
4,Hedley Mejia,1-267-247-1174,a@aol.org,"P.O. Box 461, 9908 Luctus Road",3543 LM,Provence-Alpes-Côte d'Azur,Canada,5,4,$10.49
5,Caleb Finch,1-262-522-8138,nulla.ante@hotmail.net,792-2262 Et Street,14980,North Island,Russian Federation,19,4,$76.60
14,Jason Mosley,1-762-271-9237,ipsum@outlook.edu,Ap #204-5865 Nulla Rd.,58031,Karnataka,Turkey,7,4,$18.16
17,Drake Horton,1-488-770-2162,quam.a.felis@hotmail.com,"P.O. Box 686, 5213 Iaculis Ave",215486,Tennessee,Sweden,19,4,$11.57
33,Kimberley Watson,(568) 698-6561,lacus.varius@icloud.net,Ap #847-6595 Dolor Rd.,8976,Delaware,Chile,5,4,$8.07

>Visualizando informações que faz referência a quantidade de linhas e colunas

In [13]:
df_numberrange.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 53 entries, 4 to 498
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         53 non-null     object
 1   phone        53 non-null     object
 2   email        53 non-null     object
 3   address      53 non-null     object
 4   postalZip    53 non-null     object
 5   region       53 non-null     object
 6   country      53 non-null     object
 7   list         53 non-null     int64
 8   numberrange  53 non-null     int64
 9   currency     53 non-null     object
dtypes: int64(2), object(8)
memory usage: 4.6+ KB

Criando uma nova página com 53 linhas e 10 colunas. Por enquanto no Google Sheets estará em branco

In [16]:
numberrange = spreasheet.add_worksheet('Numberrange_Data', rows=53, cols=10)

>Para inserir os dados filtrados para nova página que chamamos de "Numberrange_Data". Vamos precisar atualizar da seguinte forma nossa variável numberrange

In [17]:
numberrange.update([df_numberrange.columns.values.tolist()] + df_numberrange.values.tolist())

{'spreadsheetId': '1ta35CQlVuDHchDS6RavnCgHQnlXuRVV9t0oKTbvgB2I',
 'updatedCells': 540,
 'updatedColumns': 10,
 'updatedRange': 'Numberrange_Data!A1:J54',
 'updatedRows': 54}

Para entender um pouco mais a linha acima, veja que criamos uma lista com os nomes das colunas

In [19]:
df_numberrange.columns.values.tolist()

['name',
 'phone',
 'email',
 'address',
 'postalZip',
 'region',
 'country',
 'list',
 'numberrange',
 'currency']

>Transforma os valores do DataFrame em que tudo que não é coluna, também em uma lista

In [20]:
df_numberrange.values.tolist()

[['Hedley Mejia',
  '1-267-247-1174',
  'a@aol.org',
  'P.O. Box 461, 9908 Luctus Road',
  '3543 LM',
  "Provence-Alpes-Côte d'Azur",
  'Canada',
  5,
  4,
  '$10.49'],
 ['Caleb Finch',
  '1-262-522-8138',
  'nulla.ante@hotmail.net',
  '792-2262 Et Street',
  14980,
  'North Island',
  'Russian Federation',
  19,
  4,
  '$76.60'],
 ['Jason Mosley',
  '1-762-271-9237',
  'ipsum@outlook.edu',
  'Ap #204-5865 Nulla Rd.',
  58031,
  'Karnataka',
  'Turkey',
  7,
  4,
  '$18.16'],
 ['Drake Horton',
  '1-488-770-2162',
  'quam.a.felis@hotmail.com',
  'P.O. Box 686, 5213 Iaculis Ave',
  215486,
  'Tennessee',
  'Sweden',
  19,
  4,
  '$11.57'],
 ['Kimberley Watson',
  '(568) 698-6561',
  'lacus.varius@icloud.net',
  'Ap #847-6595 Dolor Rd.',
  8976,
  'Delaware',
  'Chile',
  5,
  4,
  '$8.07'],
 ['Hayes Chan',
  '(804) 244-3948',
  'et.rutrum.non@hotmail.net',
  '3765 Eget, Avenue',
  5384,
  'Munster',
  'South Korea',
  19,
  4,
  '$23.84'],
 ['Sopoline Higgins',
  '1-721-171-0451',
  'lorem.eu.metus@aol.ca',
  '7899 Amet St.',
  553572,
  'Niedersachsen',
  'China',
  11,
  4,
  '$14.15'],
 ['Wyoming Duncan',
  '1-884-827-7283',
  'orci@protonmail.couk',
  '438-9904 Ultricies Avenue',
  12122,
  'Cajamarca',
  'Pakistan',
  3,
  4,
  '$2.78'],
 ['Edan Irwin',
  '1-952-557-1356',
  'mauris@hotmail.org',
  '1242 Primis Road',
  8877,
  'Styria',
  'United Kingdom',
  13,
  4,
  '$30.99'],
 ['Wylie Walter',
  '1-198-995-3268',
  'suspendisse.sagittis@google.org',
  '155-1199 Blandit. Road',
  483712,
  'Kharkiv oblast',
  'China',
  5,
  4,
  '$0.73'],
 ['Courtney Robertson',
  '1-354-667-8145',
  'quam.a@outlook.ca',
  'Ap #958-8540 Aliquam Av.',
  849320,
  'Vlaams-Brabant',
  'South Korea',
  1,
  4,
  '$36.07'],
 ['Jamalia Moore',
  '1-868-851-1426',
  'etiam.imperdiet@aol.edu',
  'P.O. Box 750, 6600 At, Street',
  7858,
  'South Island',
  'Spain',
  9,
  4,
  '$9.10'],
 ['Kai Jimenez',
  '1-633-839-1963',
  'sed.diam.lorem@hotmail.ca',
  '247-4292 Purus St.',
  71245,
  'South Island',
  'France',
  3,
  4,
  '$34.98'],
 ['Hanae Weiss',
  '1-348-467-2188',
  'tincidunt.congue@google.org',
  'Ap #420-8088 Scelerisque St.',
  352555,
  'Ivano-Frankivsk oblast',
  'China',
  1,
  4,
  '$40.87'],
 ['Candice Rosario',
  '1-312-411-0518',
  'morbi.tristique.senectus@google.edu',
  '3734 Vitae, Av.',
  513532,
  'Pennsylvania',
  'South Africa',
  9,
  4,
  '$14.75'],
 ['Nathaniel Irwin',
  '(632) 711-6529',
  'erat@outlook.org',
  '712-2829 Etiam St.',
  14632,
  'Haute-Normandie',
  'Ukraine',
  1,
  4,
  '$23.74'],
 ['Devin Shields',
  '1-613-215-6716',
  'egestas.a@aol.couk',
  '292-4091 Etiam Ave',
  16316,
  'Lubelskie',
  'Philippines',
  9,
  4,
  '$67.83'],
 ['Dante Tyler',
  '(408) 299-1694',
  'est@google.ca',
  'Ap #944-7994 Porttitor Road',
  505614,
  'Volgograd Oblast',
  'Chile',
  5,
  4,
  '$90.90'],
 ['Nasim Suarez',
  '1-431-871-7405',
  'nunc.sit@google.ca',
  '1761 Integer Street',
  158342,
  'Yaroslavl Oblast',
  'Vietnam',
  3,
  4,
  '$89.38'],
 ['Ferdinand Bond',
  '1-643-799-4831',
  'non.egestas@protonmail.org',
  'Ap #813-4830 Sit Road',
  5385,
  'Aceh',
  'Indonesia',
  15,
  4,
  '$70.67'],
 ['Rooney Dickerson',
  '1-108-762-0812',
  'arcu@icloud.net',
  '3057 Dis Street',
  129245,
  'Catalunya',
  'Australia',
  15,
  4,
  '$31.67'],
 ['Brielle Castaneda',
  '(841) 569-7527',
  'mi.ac@outlook.ca',
  '5008 Eu, St.',
  'R6S 7H1',
  'Lubelskie',
  'Costa Rica',
  7,
  4,
  '$42.45'],
 ['Adam Jensen',
  '(870) 671-4934',
  'orci@yahoo.couk',
  'P.O. Box 818, 7712 Egestas. St.',
  32407,
  'Radnorshire',
  'Canada',
  5,
  4,
  '$87.98'],
 ['Dai Pickett',
  '1-732-346-5667',
  'montes.nascetur@protonmail.net',
  'Ap #731-6683 Massa. Avenue',
  'E49 7CM',
  'Balochistan',
  'Russian Federation',
  11,
  4,
  '$48.79'],
 ['Guy Gay',
  '1-518-750-3258',
  'et.netus.et@hotmail.edu',
  'P.O. Box 593, 5868 Suspendisse Av.',
  84412,
  'Hà Nội',
  'Chile',
  15,
  4,
  '$93.84'],
 ['Amery Rosa',
  '(829) 765-8312',
  'neque.vitae@outlook.ca',
  '809-1267 Suspendisse Avenue',
  810479,
  'North Gyeongsang',
  'Ireland',
  1,
  4,
  '$32.17'],
 ['Colette Mills',
  '(763) 942-8285',
  'egestas.lacinia.sed@icloud.net',
  '604-6669 Dapibus St.',
  'V8L 1M8',
  'Aquitaine',
  'Philippines',
  3,
  4,
  '$22.12'],
 ['Price Avila',
  '(194) 713-3565',
  'nonummy@protonmail.edu',
  'Ap #440-5194 Risus. Street',
  3579,
  'Overijssel',
  'Italy',
  11,
  4,
  '$54.47'],
 ['Cherokee Pennington',
  '(610) 869-3216',
  'non.luctus.sit@aol.net',
  '141 Ac Ave',
  '5562 RK',
  'Zhōngnán',
  'Brazil',
  9,
  4,
  '$43.67'],
 ['Chadwick Vega',
  '1-552-933-9384',
  'egestas.ligula@aol.couk',
  'P.O. Box 480, 8420 In Rd.',
  5238,
  'Punjab',
  'Ukraine',
  1,
  4,
  '$82.35'],
 ['Colette Mccoy',
  '(272) 646-5838',
  'vivamus.non.lorem@icloud.org',
  'Ap #381-170 Egestas. Rd.',
  8752,
  'Hidalgo',
  'Indonesia',
  11,
  4,
  '$14.58'],
 ['Shaeleigh Buchanan',
  '1-688-432-4174',
  'aenean@yahoo.edu',
  'P.O. Box 474, 7244 Hendrerit Road',
  9085,
  'Uttar Pradesh',
  'Austria',
  1,
  4,
  '$72.68'],
 ['August Curtis',
  '(753) 256-5355',
  'quisque.nonummy@icloud.net',
  'P.O. Box 678, 8097 Gravida. Ave',
  8305,
  'Agder',
  'Singapore',
  1,
  4,
  '$70.85'],
 ['Cynthia Mullen',
  '(532) 272-7706',
  'ullamcorper.velit@hotmail.edu',
  '7171 Cursus, Avenue',
  1627,
  'Volgograd Oblast',
  'France',
  19,
  4,
  '$7.66'],
 ['Lacey Gibson',
  '(135) 324-1588',
  'hendrerit.consectetuer@yahoo.edu',
  '143-3288 Orci Avenue',
  '82-118',
  'Guanajuato',
  'Russian Federation',
  13,
  4,
  '$59.58'],
 ['Cade Johns',
  '1-285-422-4888',
  'facilisis@hotmail.ca',
  '704 Curae Avenue',
  3747,
  'New South Wales',
  'Turkey',
  5,
  4,
  '$8.71'],
 ['Pearl Bush',
  '1-278-656-7730',
  'lorem.donec@google.couk',
  'P.O. Box 460, 997 Cursus St.',
  797813,
  'Queensland',
  'Peru',
  5,
  4,
  '$86.46'],
 ['Adele Moody',
  '1-324-718-7366',
  'sit.amet@yahoo.couk',
  'Ap #239-8413 In Road',
  '79125-16058',
  'Burgenland',
  'Netherlands',
  15,
  4,
  '$55.20'],
 ['Mallory Buchanan',
  '1-718-844-4422',
  'vulputate.dui@google.org',
  '423-6899 Adipiscing. St.',
  6117,
  'Limpopo',
  'Russian Federation',
  5,
  4,
  '$50.87'],
 ['Shaine Heath',
  '(659) 818-4868',
  'libero@yahoo.ca',
  'Ap #499-6170 Tempor Street',
  57967,
  'Lower Austria',
  'Turkey',
  13,
  4,
  '$10.52'],
 ['Nola Rios',
  '(786) 565-9673',
  'nulla.interdum@outlook.couk',
  '257-1663 Elit Rd.',
  287997,
  'Selkirkshire',
  'Norway',
  11,
  4,
  '$39.18'],
 ['Dominique Lyons',
  '1-737-269-2374',
  'curae.phasellus@protonmail.org',
  '441-7532 Auctor St.',
  56227,
  'Oost-Vlaanderen',
  'Netherlands',
  19,
  4,
  '$33.82'],
 ['Cedric Stanton',
  '1-467-955-3867',
  'praesent.eu@aol.ca',
  'P.O. Box 519, 1849 Nec, Road',
  5972,
  'Swiętokrzyskie',
  'Germany',
  7,
  4,
  '$63.62'],
 ['Janna Mcbride',
  '(233) 727-3774',
  'nunc.mauris@yahoo.com',
  'Ap #168-7515 Cras St.',
  '66-76',
  'West Region',
  'Belgium',
  13,
  4,
  '$42.08'],
 ['Hiram Leon',
  '(214) 744-6764',
  'arcu.vivamus@outlook.edu',
  '412-2391 Lacus. Rd.',
  'z4P 7S8',
  'Imo',
  'Russian Federation',
  7,
  4,
  '$59.17'],
 ['Quamar Frazier',
  '1-251-631-4775',
  'elit.nulla.facilisi@aol.net',
  'Ap #519-2391 Nunc Rd.',
  658682,
  'Vienna',
  'Italy',
  7,
  4,
  '$31.46'],
 ['Piper Holcomb',
  '(256) 753-6211',
  'in@outlook.com',
  '8786 Cubilia Rd.',
  '37-29',
  'Connacht',
  'Belgium',
  9,
  4,
  '$91.34'],
 ['Keelie Stout',
  '(167) 666-0116',
  'aliquam.nisl@yahoo.edu',
  'Ap #302-2632 Elit, Street',
  '5113-8274',
  'Swiętokrzyskie',
  'Russian Federation',
  3,
  4,
  '$9.49'],
 ['Priscilla Pacheco',
  '1-477-539-7236',
  'pharetra@outlook.couk',
  '664-8672 Ornare, Street',
  27337,
  'Ilocos Region',
  'China',
  1,
  4,
  '$35.17'],
 ['Hadassah Morales',
  '(548) 476-0331',
  'lacinia.vitae.sodales@outlook.com',
  '475-1364 Vitae, Road',
  1519,
  'Queensland',
  'United Kingdom',
  3,
  4,
  '$81.80'],
 ['Nola Forbes',
  '1-378-725-5958',
  'turpis.vitae.purus@icloud.com',
  '9093 Porttitor Street',
  'XO7P 5HJ',
  'South Kalimantan',
  'South Africa',
  1,
  4,
  '$21.85'],
 ['Oliver Cantu',
  '1-516-163-5454',
  'rutrum@yahoo.edu',
  '646-8516 Ac St.',
  1837,
  'Franche-Comté',
  'Indonesia',
  1,
  4,
  '$70.92'],
 ['Signe Shannon',
  '1-656-860-4687',
  'dapibus@outlook.edu',
  '4932 Sit St.',
  'K10 2DR',
  'Oklahoma',
  'Mexico',
  7,
  4,
  '$92.16']]

# Resultado da extração para uma nova página

>Você pode verificar o resultado da página gerada com os Numberrange igual a 4 em: [Numberrange_Data](https://docs.google.com/spreadsheets/d/1ta35CQlVuDHchDS6RavnCgHQnlXuRVV9t0oKTbvgB2I/edit#gid=1930327076)